<?xml version="1.0"?>

<robot name="ylo2_description" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="floating_base_link" default="true"/>
    <xacro:arg name="robot_name"  default="ylo2"/>
    <xacro:arg name="base_name"   default="trunk"/>

    <xacro:include filename="$(find ylo2_description)/urdfs/const.xacro"/>
    <xacro:include filename="$(find ylo2_description)/urdfs/leg.xacro"/>
    <xacro:include filename="$(find a1_description)/xacro/gazebo.xacro"/>

    <!-- Floating-base Joint -->
    <xacro:if value="$(arg floating_base_link)">
            <link name="world"/>
            <joint name="floating_base_joint" type="floating">
              <origin rpy="0 0 0" xyz="0 0 0"/>
              <parent link="world"/>
              <child link="trunk"/>
            </joint>
    </xacro:if>

    <link name="trunk">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} 0 ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_textured_body.dae" scale="1 1 1"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} 0 ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/covers_collision.stl" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
            <mass value="${trunk_mass}"/>
            <inertia
                ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}"
                iyy="${trunk_iyy}" iyz="${trunk_iyz}"
                izz="${trunk_izz}"/>  
        </inertial>
    </link>

    <link name="abad_motors">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} ${trunk_offset_y} ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_textured_abad_motors.dae" scale="1 1 1"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <joint name="abad_motors_joint" type="fixed">
        <parent link="trunk"/>
        <child link="abad_motors"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="battery">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} ${trunk_offset_y} ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/battery.stl" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="battery_joint" type="fixed">
        <parent link="trunk"/>
        <child link="battery"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="covers">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} ${trunk_offset_y} ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_textured_cover.dae" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
    </link>

    <joint name="covers_joint" type="fixed">
        <parent link="trunk"/>
        <child link="covers"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="accessories">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} ${trunk_offset_y} ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/accessories.dae" scale="1 1 1"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="accessories_joint" type="fixed">
        <parent link="trunk"/>
        <child link="accessories"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="D435">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x} ${trunk_offset_y+0.004} ${abab_motors_offset_z}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_d435_textured.dae" scale="1 1 1"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="D435_joint" type="fixed">
        <parent link="trunk"/>
        <child link="D435"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="T265">
        <visual>
            <origin rpy="0 0 0" xyz="${trunk_offset_x+0.001} ${trunk_offset_y+0.0025} ${abab_motors_offset_z+0.00}"/>
            <geometry>
                <mesh filename="package://ylo2_description/meshes/body/textured/ylo2_t265_textured.dae" scale="1 1.06 1.04"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="T265_joint" type="fixed">
        <parent link="trunk"/>
        <child link="T265"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <joint name="imu_joint" type="fixed">
        <parent link="trunk"/>
        <child link="trunk_imu"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="trunk_imu">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision>
    </link>

    <!-- ABAD POSITION OK pas touche-->
    <xacro:leg name="0" mirror="1" mirror_dae="True" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x-0.019} ${0+leg_offset_y+0.006} ${0-leg_offset_z}"/>
    </xacro:leg>

    <xacro:leg name="1" mirror="1" mirror_dae="True" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x-0.019} ${0+leg_offset_y+0.006} ${0-leg_offset_z}"/>
    </xacro:leg>

    <xacro:leg name="2" mirror="-1" mirror_dae= "False" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x-0.019} ${0-leg_offset_y+0.006} ${0-leg_offset_z}"/>
    </xacro:leg>
    
    <xacro:leg name="3" mirror="-1" mirror_dae="False" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x-0.019} ${0-leg_offset_y+0.006} ${0-leg_offset_z}"/>
    </xacro:leg>

</robot>
