
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

# Position Controllers ---------------------------------------
  joint_controller:
    type: effort_controllers/QuadController
    joints: ['0','1','2','3','4','5','6','7','8','9','10','11']

contact_state_publisher:
  update_rate: 500